// AI Coding
/**
 * @file TermsOfServicePage.tsx
 * @description Trang Điều khoản Dịch vụ (Terms of Service) của LoyaWin.
 */
import {
  LegalLayout,
  LegalParagraph,
  LegalHeading2,
  LegalList,
  LegalListItem,
} from "../components/LegalLayout";

export function TermsOfServicePage() {
  return (
    <LegalLayout
      label="Legal &amp; Terms"
      title="Terms of Service"
      effectiveDate="July 08, 2026"
    >
      <LegalParagraph>
        Welcome to LoyaWin. These Terms of Service are a legal agreement between you (representing your Brand/Business, hereinafter referred to as the &quot;Brand&quot;) and LoyaWin. By registering an account at LoyaWin or using our services, you acknowledge that you agree to be bound by these Terms.
      </LegalParagraph>

      <LegalHeading2>1. Account Registration and Security</LegalHeading2>
      <LegalList>
        <LegalListItem>
          <strong>Age &amp; Representation:</strong> The individual registering the account must be at least 18 years of age and possess full legal authority to represent the business/brand.
        </LegalListItem>
        <LegalListItem>
          <strong>Accuracy of Information:</strong> You commit to providing accurate, complete, and up-to-date registration details. Providing false information may result in the immediate termination of your account.
        </LegalListItem>
        <LegalListItem>
          <strong>Security Responsibility:</strong> You are solely responsible for maintaining the confidentiality of your password and account credentials, including all staff accounts created under your brand. Please notify us immediately of any unauthorized access.
        </LegalListItem>
      </LegalList>

      <LegalHeading2>2. Service Description and License</LegalHeading2>
      <LegalParagraph>
        LoyaWin provides cloud-based software solutions including:
      </LegalParagraph>
      <LegalList>
        <LegalListItem>
          Tools to create and manage digital membership cards for customers.
        </LegalListItem>
        <LegalListItem>
          Real-time store configurations, point collection, point redemption, and rewards at cashier counters.
        </LegalListItem>
        <LegalListItem>
          Self-service advertising tools displayed on the membership application of customers.
        </LegalListItem>
      </LegalList>
      <LegalParagraph>
        We grant you a limited, non-exclusive, non-transferable, and revocable license to use our services in accordance with these Terms.
      </LegalParagraph>

      <LegalHeading2>3. Payments and Taxes (Paddle as payment partner)</LegalHeading2>
      <LegalList>
        <LegalListItem>
          <strong>Authorized Payment Partner:</strong> All Subscription and Ads transactions on LoyaWin are processed directly through <strong>Paddle.com</strong> – our authorized Merchant of Record (MoR).
        </LegalListItem>
        <LegalListItem>
          <strong>Auto-Billing Authorization:</strong> Linking your payment method implies that you authorize Paddle to process automatic recurring payments in accordance with your selected billing cycle.
        </LegalListItem>
        <LegalListItem>
          <strong>Taxes:</strong> Listed prices do not include VAT or local consumer taxes. These taxes will be automatically calculated and applied by Paddle at checkout based on your country and tax identification details.
        </LegalListItem>
        <LegalListItem>
          <strong>Tax Invoices:</strong> Official PDF invoices will be automatically generated by Paddle and sent directly to your email address after each successful transaction.
        </LegalListItem>
      </LegalList>

      <LegalHeading2>4. Duration, Cancellation, and Suspension</LegalHeading2>
      <LegalList>
        <LegalListItem>
          <strong>Cancellation (Cancel Subscription):</strong> You can cancel your subscription renewal at any time via the billing management section in the brand portal, which redirects you to Paddle.
          <ul className="pl-6 mt-2 space-y-1.5 list-disc text-slate-500 text-sm">
            <li><strong>Grace Period:</strong> Upon cancellation, your account will remain active and you will continue to have full access to all features of the subscription until the end of the current billing cycle. Auto-renewal status will be displayed as <strong>Inactive</strong>, and no future charges will be applied.</li>
          </ul>
        </LegalListItem>
        <LegalListItem>
          <strong>Expiration (Expired – View-only Mode):</strong> If a billing cycle ends and the subscription is not successfully renewed (either after a failed payment or manual cancellation):
          <ul className="pl-6 mt-2 space-y-1.5 list-disc text-slate-500 text-sm">
            <li>The brand portal will automatically switch to <strong>View-only</strong> mode. You can still log in to view historical data and download invoices, but you cannot create, edit, or delete any data.</li>
            <li>All connected store branches and staff accounts will be temporarily suspended from points operations, and active terminals will be automatically logged out.</li>
            <li>Full functionality will be restored immediately upon a successful renewal payment via the <strong>Renew Subscription</strong> button.</li>
          </ul>
        </LegalListItem>
      </LegalList>

      <LegalHeading2>5. Acceptable Use Policy</LegalHeading2>
      <LegalParagraph>
        You agree NOT to engage in any of the following activities:
      </LegalParagraph>
      <LegalList>
        <LegalListItem>
          Collect or accumulate points for fraudulent, fake, or illegal purchase invoices.
        </LegalListItem>
        <LegalListItem>
          Upload advertising content that violates local laws, is obscene, violent, offensive, or infringes upon the intellectual property or trademarks of third parties.
        </LegalListItem>
        <LegalListItem>
          Interfere with, disrupt, overload, or attempt to gain unauthorized access to LoyaWin's database or cloud infrastructure.
        </LegalListItem>
      </LegalList>

      <LegalHeading2>6. Limitation of Liability and Indemnification</LegalHeading2>
      <LegalList>
        <LegalListItem>
          <strong>&quot;As-Is&quot; Service:</strong> LoyaWin provides its software on an &quot;as-is&quot; and &quot;as-available&quot; basis, without guarantees that the service will be entirely error-free or uninterrupted.
        </LegalListItem>
        <LegalListItem>
          <strong>Maximum Liability:</strong> Our maximum cumulative liability for any damages arising out of the use of the services shall not exceed the actual amount paid by you to LoyaWin during the last one (1) month preceding the claim event.
        </LegalListItem>
        <LegalListItem>
          <strong>Indemnification:</strong> LoyaWin only provides the software tool. Any disputes or claims regarding transaction invoices or product quality between the Brand and its end-customers shall be resolved directly between those parties; LoyaWin is fully indemnified from any related liability.
        </LegalListItem>
      </LegalList>

      <LegalHeading2>7. Governing Law and Dispute Resolution</LegalHeading2>
      <LegalList>
        <LegalListItem>
          <strong>Governing Law:</strong> These Terms of Service and any legal relationships arising from the use of the services shall be governed by and construed in accordance with the laws of the Federal Republic of Germany, excluding the United Nations Convention on Contracts for the International Sale of Goods (CISG).
        </LegalListItem>
        <LegalListItem>
          <strong>Jurisdiction:</strong> If the Brand is a merchant (Kaufmann), a legal entity under public law, or a special fund under public law, the exclusive venue for all disputes arising out of or in connection with this agreement shall be the competent court in the city where LoyaWin has its registered office in Germany.
        </LegalListItem>
        <LegalListItem>
          <strong>EU Online Dispute Resolution (ODR):</strong> The European Commission provides an online dispute resolution platform for consumers (in case of end-customer disputes), accessible at: <a href="https://ec.europa.eu/consumers/odr" target="_blank" rel="noopener noreferrer" className="text-[var(--loyawin-primary)] hover:underline">https://ec.europa.eu/consumers/odr</a>. We are not obliged and are not willing to participate in dispute resolution proceedings before a consumer arbitration board.
        </LegalListItem>
      </LegalList>

      <LegalHeading2>8. Changes to Terms</LegalHeading2>
      <LegalParagraph>
        Significant changes to these Terms will be communicated to you via a dashboard banner or email at least seven (7) days prior to the effective date.
      </LegalParagraph>

      <LegalHeading2>9. Contact Information</LegalHeading2>
      <LegalParagraph>
        If you have any questions regarding these Terms, please contact us:
      </LegalParagraph>
      <LegalList>
        <LegalListItem>
          <strong>Support Email:</strong> support@loyawin.com
        </LegalListItem>
      </LegalList>
    </LegalLayout>
  );
}
